Fixed #23
exasol/athena-virtual-schema pull request #24
Opened 2023-04-19 13:22 UTC by ckunki

fixes #23

2023-04-20 06:11 UTC, redcatbear submitted a review, later dismissed

2023-04-20 06:11 UTC, redcatbear commented on src/main/java/com/exasol/adapter/dialects/athena/AthenaIdentifier.java
> +     * Only required for {@code CREATE TABLE} statements.
```suggestion
    /**
     * Quote a given identifier with backticks ({@code `}).
     * <p>
     * Only required for {@code CREATE TABLE} statements.
     * </p>
```

2023-04-20 07:31 UTC, kaklakariada requested changes

2023-04-20 07:31 UTC, kaklakariada commented on pom.xml
>          <repository>
Delete the maven.exasol.com repo

2023-04-20 09:41 UTC, kaklakariada approved these changes, later dismissed

2023-04-21 05:18 UTC, kaklakariada approved these changes

2023-04-21 05:34 UTC, merged